/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/interrogation_room.glb -o src/components/Room.jsx -r public 
Author: local.yany (https://sketchfab.com/local.yany)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/interrogation-room-7447d64fe2dc493486b8f56628bc6d30
Title: Interrogation room
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Room(props) {
  const { nodes, materials } = useGLTF('/models/interrogation_room.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[32.152, 0, 75.608]}>
          <mesh geometry={nodes.Polygraph_54117Shape_Paper_0.geometry} material={materials.Paper} />
          <mesh geometry={nodes.Polygraph_54117Shape_WhiteRing_0.geometry} material={materials.WhiteRing} />
          <mesh geometry={nodes.Polygraph_54117Shape_BlackRubber_0.geometry} material={materials.BlackRubber} />
          <mesh geometry={nodes.Polygraph_54117Shape_BlackMetal_0.geometry} material={materials.BlackMetal} />
          <mesh geometry={nodes.Polygraph_54117Shape_needle_0.geometry} material={materials.needle} />
          <mesh geometry={nodes.Polygraph_54117Shape_yellow_0.geometry} material={materials.yellow} />
          <mesh geometry={nodes.Polygraph_54117Shape_Brass_0.geometry} material={materials.Brass} />
          <mesh geometry={nodes.Polygraph_54117Shape_Blue_0.geometry} material={materials.Blue} />
          <mesh geometry={nodes.Polygraph_54117Shape_Plastic_0.geometry} material={materials.Plastic} />
          <mesh geometry={nodes.Polygraph_54117Shape_Steel1_0.geometry} material={materials.Steel1} />
          <mesh geometry={nodes.Polygraph_54117Shape_BlacKFace_0.geometry} material={materials.BlacKFace} />
          <mesh geometry={nodes.Polygraph_54117Shape_Glass_0.geometry} material={materials.Glass} />
        </group>
        <group position={[0, -2.06, 0]}>
          <mesh geometry={nodes.Cup_2056Shape_Coffee_0.geometry} material={materials.Coffee} />
          <mesh geometry={nodes.Cup_2056Shape_CoffeeCup_0.geometry} material={materials.CoffeeCup} />
        </group>
        <group position={[0, -0.967, 0]}>
          <group position={[0, -0.089, 0]}>
            <mesh geometry={nodes.Pen_275Shape_Pen_0.geometry} material={materials.material} />
            <mesh geometry={nodes.Pen_275Shape_PenTip_0.geometry} material={materials.PenTip} />
          </group>
          <mesh geometry={nodes.Document_8Shape_Doc_0.geometry} material={materials.material_16} />
        </group>
        <mesh geometry={nodes.Table_776Shape_Table_0.geometry} material={materials.Table} />
        <mesh geometry={nodes.LeftWall_15332Shape_Walls_0.geometry} material={materials.Walls} />
        <mesh geometry={nodes.LeftWall_15332Shape_PipeFittings_0.geometry} material={materials.PipeFittings} />
        <mesh geometry={nodes.LeftWall_15332Shape_Pipe_0.geometry} material={materials.Pipe} />
        <mesh geometry={nodes.LeftWall_15332Shape_RunnerBoards_0.geometry} material={materials.RunnerBoards} />
        <mesh geometry={nodes.BackWall2_1888Shape_Frame_0.geometry} material={materials.Frame} />
        <mesh geometry={nodes.BackWall2_1888Shape_Metal_0.geometry} material={materials.Metal} />
        <mesh geometry={nodes.BackWall2_1888Shape_White_0.geometry} material={materials.White} />
        <mesh geometry={nodes.BackWall2_1888Shape_Wall_0.geometry} material={materials.Wall} />
        <mesh geometry={nodes.BackWall2_1888Shape_Glass_0.geometry} material={materials.Glass_0} />
        <mesh geometry={nodes.RightWall_294Shape_Walls_0.geometry} material={materials.Walls_0} />
        <mesh geometry={nodes.RightWall_294Shape_Mirror_0.geometry} material={materials.Mirror} />
        <mesh geometry={nodes.RightWall_294Shape_RunnerBoards_0.geometry} material={materials.RunnerBoards_0} />
        <mesh geometry={nodes.RightWall_294Shape_MirrorFrame_0.geometry} material={materials.MirrorFrame} />
        <mesh geometry={nodes.chair_2012Shape_Chair_0.geometry} material={materials.Chair} />
        <group position={[231.635, 0, 0]} rotation={[0, 1.058, 0]}>
          <mesh geometry={nodes.Camera_14551Shape_Camera_0.geometry} material={materials.Camera} />
          <mesh geometry={nodes.Camera_14551Shape_Lens_0.geometry} material={materials.Lens} />
        </group>
        <group position={[337.516, 0, 0]} rotation={[0, 1.058, 0]}>
          <mesh geometry={nodes.Camera_14551_dup_2Shape_Camera_0.geometry} material={materials.Camera_0} />
          <mesh geometry={nodes.Camera_14551_dup_2Shape_Lens_0.geometry} material={materials.Lens_0} />
        </group>
        <group position={[97.179, 0, 514.885]} rotation={[0, 0.777, 0]}>
          <mesh geometry={nodes.Camera_14551_dup_3Shape_Camera_0.geometry} material={materials.Camera_1} />
          <mesh geometry={nodes.Camera_14551_dup_3Shape_Lens_0.geometry} material={materials.Lens_1} />
        </group>
        <mesh geometry={nodes.Light_536Shape_LightFittingReflector_0.geometry} material={materials.LightFittingReflector} />
        <mesh geometry={nodes.Light_536Shape_LightTube_0.geometry} material={materials.LightTube} />
        <mesh geometry={nodes.Ceiling_9Shape_Ceiling_0.geometry} material={materials.Ceiling} />
        <mesh geometry={nodes.Floor_4Shape_Floor_0.geometry} material={materials.Floor} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/interrogation_room.glb')
